[Icon Theme]
Name=Faenza
Inherits=Adwaita,gnome,hicolor
Comment=slightly modified Adwaita
Directories=actions/scalable,actions/symbolic,apps/48, apps/48

[actions/scalable]
Context=Actions
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[actions/symbolic]
Size=16
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[apps/48]
Context=Apps
Size=48
Type=Scalable

[apps/64]
Context=Apps
Size=64
Type=Scalable

